language: node_js
node_js:
  - '8'
  - '6'

sudo: false

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server

after_success: npm run coveralls
