language: node_js
node_js:
  - 'stable'
  - '1'
  - '2'
  - '3'

sudo: false
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-trusty
    packages:
      - mongodb-org-server
      - mongodb-org-shell
