// Generated by CoffeeScript 1.3.1
var Mongorito, Post;

Mongorito = require('../lib/mongorito');

Mongorito.connect(['mongo://127.0.0.1:27017/databaseName']);

Post = (function() {

  Post.name = 'Post';

  function Post() {}

  Post.prototype.keys = ['author', 'content', 'title'];

  Post.prototype.scopes = {
    byDrew: {
      author: 'Drew'
    },
    one: {
      limit: 1
    }
  };

  return Post;

})();

Post = Mongorito.bake(Post);

Post.one(function(err, posts) {
  return posts.length === 1;
});

Post.byDrew(function(err, posts) {});
